const { supabaseAdmin } = require("../config/supabase");
const { notifyRegisterUser } = require("./registerNotificationService");

const FREQUENCIES = ["Weekly","Monthly","Every N months","Quarterly","Half-yearly","Annual","Custom interval"];
const BILLING = ["Per work","Monthly","Quarterly","Half-yearly","Annual","No automatic billing"];
const RULES = ["Fixed day in same month","Fixed day in following month","N days after period end","Fixed annual date","Custom manual date"];
const MANAGERS = ["Admin","Manager","Staff Manager"];
const clean = (value, max = 4000) => String(value ?? "").trim().slice(0, max);
const fail = (message, status = 400) => Object.assign(new Error(message), { status });
const canManage = (profile = {}) => MANAGERS.includes(profile.role);
const dateOnly = (value) => /^\d{4}-\d{2}-\d{2}$/.test(String(value || "")) ? String(value) : "";
const isoDate = (date) => new Date(date).toISOString().slice(0, 10);

function addDays(date, amount) { const d = new Date(`${date}T00:00:00Z`); d.setUTCDate(d.getUTCDate() + Number(amount || 0)); return isoDate(d); }
function addMonths(date, amount) { const d = new Date(`${date}T00:00:00Z`); const day = d.getUTCDate(); d.setUTCDate(1); d.setUTCMonth(d.getUTCMonth() + amount); const last = new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth() + 1, 0)).getUTCDate(); d.setUTCDate(Math.min(day, last)); return isoDate(d); }
function periodEnd(start, frequency, interval = 1) {
  if (frequency === "Weekly") return addDays(start, 6);
  if (frequency === "Custom interval") return addDays(start, Math.max(1, interval) - 1);
  const months = frequency === "Quarterly" ? 3 : frequency === "Half-yearly" ? 6 : frequency === "Annual" ? 12 : frequency === "Every N months" ? Math.max(1, interval) : 1;
  return addDays(addMonths(start, months), -1);
}
function nextPeriod(start, frequency, interval = 1) {
  if (frequency === "Weekly") return addDays(start, 7);
  if (frequency === "Custom interval") return addDays(start, Math.max(1, interval));
  return addMonths(start, frequency === "Quarterly" ? 3 : frequency === "Half-yearly" ? 6 : frequency === "Annual" ? 12 : frequency === "Every N months" ? Math.max(1, interval) : 1);
}
function financialYear(date) { const d = new Date(`${date}T00:00:00Z`); const y = d.getUTCFullYear(); const first = d.getUTCMonth() >= 3 ? y : y - 1; return `${first}-${String(first + 1).slice(-2)}`; }
function periodLabel(start, frequency, interval = 1) {
  const d = new Date(`${start}T00:00:00Z`); const fy = financialYear(start); const month = d.getUTCMonth() + 1;
  if (["Monthly","Every N months"].includes(frequency)) return d.toLocaleDateString("en-IN", { month: "long", year: "numeric", timeZone: "UTC" });
  if (frequency === "Quarterly") return `Q${month >= 4 && month <= 6 ? 1 : month >= 7 && month <= 9 ? 2 : month >= 10 ? 3 : 4} FY ${fy}`;
  if (frequency === "Half-yearly") return `${month >= 4 && month <= 9 ? "H1" : "H2"} FY ${fy}`;
  if (frequency === "Annual") return `FY ${fy}`;
  return `${start} to ${periodEnd(start, frequency, interval)}`;
}
function ruleDate(start, end, rule = {}) {
  const type = RULES.includes(rule.type) ? rule.type : "N days after period end";
  const base = new Date(`${end}T00:00:00Z`); const day = Math.min(31, Math.max(1, Number(rule.day) || 1));
  if (type === "Custom manual date" && dateOnly(rule.date)) return rule.date;
  if (type === "N days after period end") return addDays(end, Number(rule.days) || 0);
  if (type === "Fixed annual date") return `${Number(rule.year) || base.getUTCFullYear()}-${String(Math.min(12,Math.max(1,Number(rule.month)||12))).padStart(2,"0")}-${String(day).padStart(2,"0")}`;
  const target = new Date(Date.UTC(base.getUTCFullYear(), base.getUTCMonth() + (type === "Fixed day in following month" ? 1 : 0), 1));
  const last = new Date(Date.UTC(target.getUTCFullYear(), target.getUTCMonth() + 1, 0)).getUTCDate(); target.setUTCDate(Math.min(day,last)); return isoDate(target);
}
function normalizeRule(input, prefix, fallbackDays) {
  const direct = input[prefix] && typeof input[prefix] === "object" ? input[prefix] : {};
  const type = clean(input[`${prefix}Type`] || direct.type) || "N days after period end";
  if (!RULES.includes(type)) throw fail(`Invalid ${prefix.replace(/([A-Z])/g," $1").toLowerCase()}.`);
  return { type, day: Number(input[`${prefix}Day`] ?? direct.day) || undefined, days: Number(input[`${prefix}Days`] ?? direct.days) || fallbackDays, month: Number(input[`${prefix}Month`] ?? direct.month) || undefined, year: Number(input[`${prefix}Year`] ?? direct.year) || undefined, date: dateOnly(input[`${prefix}Date`] || direct.date) || undefined };
}
async function audit(scheduleId, action, req, oldValue = null, newValue = null, occurrenceId = null) {
  const { error } = await supabaseAdmin.from("recurring_work_audit").insert({ schedule_id: scheduleId, occurrence_id: occurrenceId, action, old_value: oldValue, new_value: newValue, actor_user_id: req?.user?.id || null, actor_name: req?.profile?.name || req?.profile?.email || "System" });
  if (error) throw error;
}
function visible(query, profile) { return canManage(profile) ? query : query.eq("assigned_staff_id", profile.id); }

async function listSchedules(filters = {}, profile = {}) {
  const page = Math.max(1, Number(filters.page) || 1); const pageSize = Math.min(100, Math.max(10, Number(filters.pageSize) || 25));
  let query = supabaseAdmin.from("recurring_work_schedules").select("*,assigned:app_users!recurring_work_schedules_assigned_staff_id_fkey(id,name,email),reviewer:app_users!recurring_work_schedules_reviewer_id_fkey(id,name,email)", { count: "exact" });
  query = visible(query, profile);
  if (filters.view === "active") query = query.eq("active", true).eq("paused", false).is("ended_at", null);
  if (filters.view === "paused") query = query.eq("paused", true);
  if (filters.clientId) query = query.eq("client_id", filters.clientId);
  if (filters.service) query = query.eq("service_type", filters.service);
  if (filters.staffId) query = query.eq("assigned_staff_id", filters.staffId);
  const q = clean(filters.q, 120).replace(/[,%()]/g, " "); if (q) query = query.or(`client_name.ilike.%${q}%,service_type.ilike.%${q}%,work_type.ilike.%${q}%`);
  const from = (page - 1) * pageSize; const { data, error, count } = await query.order("next_generation_date").range(from, from + pageSize - 1); if (error) throw error;
  return { schedules: data || [], total: count || 0, page, pageSize, pageCount: Math.max(1, Math.ceil((count || 0) / pageSize)) };
}
async function getSchedule(id, profile) {
  let query = supabaseAdmin.from("recurring_work_schedules").select("*,assigned:app_users!recurring_work_schedules_assigned_staff_id_fkey(id,name,email),reviewer:app_users!recurring_work_schedules_reviewer_id_fkey(id,name,email)").eq("id", id); query = visible(query, profile);
  const { data, error } = await query.maybeSingle(); if (error) throw error; if (!data) throw fail("Recurring schedule not found or access denied.", 404);
  const [{ data: occurrences, error: occurrenceError }, { data: history, error: historyError }] = await Promise.all([supabaseAdmin.from("recurring_work_occurrences").select("*").eq("recurring_schedule_id", id).order("created_at", { ascending: false }).limit(100), supabaseAdmin.from("recurring_work_audit").select("*").eq("schedule_id", id).order("created_at", { ascending: false }).limit(100)]); if (occurrenceError) throw occurrenceError; if (historyError) throw historyError;
  return { schedule: data, occurrences: occurrences || [], history: history || [] };
}
async function schedulePayload(input, existing = {}) {
  const clientId = input.clientId || input.client_id || existing.client_id; const serviceType = clean(input.serviceType || input.service_type || existing.service_type, 160); const workType = clean(input.workType || input.work_type || existing.work_type, 160); const frequency = input.frequency || existing.frequency; const startDate = dateOnly(input.startDate || input.start_date || existing.start_date);
  if (!serviceType || !workType || !FREQUENCIES.includes(frequency) || !startDate) throw fail("Client, Service, Work Type, Frequency and Start Period are required.");
  let clientQuery = supabaseAdmin.from("clients").select("id,client_name,pan_reg_no,status");
  if (clientId) clientQuery = clientQuery.eq("id", clientId);
  else if (clean(input.panRegNo || input.pan_reg_no, 40)) clientQuery = clientQuery.eq("normalized_pan", clean(input.panRegNo || input.pan_reg_no, 40).toUpperCase().replace(/[^A-Z0-9]/g,""));
  else if (clean(input.clientName || input.client_name, 240)) clientQuery = clientQuery.ilike("client_name", clean(input.clientName || input.client_name, 240));
  else throw fail("Client is required.");
  const { data: clients, error } = await clientQuery.limit(2); if (error) throw error; if (!clients?.length) throw fail("The client was not found in Client Master."); if (clients.length > 1) throw fail("Multiple clients match this row. Use Client ID or PAN."); const client=clients[0]; if (client.status !== "Active") throw fail("Recurring work can only be created for an active client.");
  const intervalValue = Math.max(1, Number(input.intervalValue || input.interval_value || existing.interval_value) || 1); const dueRule = normalizeRule(input, "dueDateRule", 0); const internalRule = normalizeRule(input, "internalTargetRule", -3); const documentRule = normalizeRule(input, "documentDueRule", -7); const end = periodEnd(startDate, frequency, intervalValue); const due = ruleDate(startDate, end, dueRule); const lead = Math.max(0, Number(input.generateBeforeDays ?? input.generate_before_days ?? existing.generate_before_days) || 0); const generationDate = addDays(due, -lead);
  const checklist = Array.isArray(input.checklist) ? input.checklist : clean(input.checklistText || "").split(/\r?\n|,/).map((x) => x.trim()).filter(Boolean);
  return { client_id: client.id, client_name: client.client_name, pan_reg_no: client.pan_reg_no, service_type: serviceType, work_type: workType, return_type: clean(input.returnType || input.return_type || existing.return_type,160) || null, description: clean(input.description || existing.description,4000) || null, frequency, interval_value: intervalValue, start_date: startDate, start_period: clean(input.startPeriod || input.start_period,80) || periodLabel(startDate,frequency,intervalValue), next_period_start: existing.next_period_start || startDate, end_date: dateOnly(input.endDate || input.end_date) || null, occurrence_limit: Number(input.occurrenceLimit || input.occurrence_limit) || null, next_generation_date: existing.next_generation_date || `${generationDate}T00:00:00.000Z`, next_work_period: existing.next_work_period || periodLabel(startDate,frequency,intervalValue), due_date_rule: dueRule, internal_target_rule: internalRule, document_due_rule: documentRule, holiday_rule: input.holidayRule || input.holiday_rule || existing.holiday_rule || "Keep original date", generate_before_days: lead, assignment_type: input.assignmentType || input.assignment_type || existing.assignment_type || "Fixed employee", assigned_staff_id: input.assignedStaffId || input.assigned_staff_id || null, assigned_team: clean(input.assignedTeam || input.assigned_team,160) || null, reviewer_id: input.reviewerId || input.reviewer_id || null, priority: input.priority || "Medium", estimated_completion_days: Number(input.estimatedCompletionDays || input.estimated_completion_days) || null, standard_fee: input.standardFee === "" ? null : Number(input.standardFee ?? input.standard_fee) || null, productivity_weight: Number(input.productivityWeight || input.productivity_weight) || 1, billing_frequency: BILLING.includes(input.billingFrequency || input.billing_frequency) ? (input.billingFrequency || input.billing_frequency) : "No automatic billing", checklist, remarks: clean(input.remarks,10000) || null, updated_at: new Date().toISOString() };
}
async function createSchedule(input, req) { if (!canManage(req.profile)) throw fail("Only authorized managers can create recurring schedules.",403); const payload = await schedulePayload(input); payload.created_by=req.user.id; payload.updated_by=req.user.id; const { data,error }=await supabaseAdmin.from("recurring_work_schedules").insert(payload).select("*").single(); if(error?.code==="23505") throw fail("A matching recurring schedule already exists.",409); if(error) throw error; await audit(data.id,"Schedule created",req,null,data); return getSchedule(data.id,req.profile); }
async function updateSchedule(id,input,req) { if(!canManage(req.profile)) throw fail("Only authorized managers can edit recurring schedules.",403); const { schedule: before }=await getSchedule(id,req.profile); const payload=await schedulePayload(input,before); payload.updated_by=req.user.id; delete payload.next_period_start; delete payload.next_generation_date; delete payload.next_work_period; const {data,error}=await supabaseAdmin.from("recurring_work_schedules").update(payload).eq("id",id).select("*").single(); if(error) throw error; await audit(id,"Schedule edited",req,before,data); return getSchedule(id,req.profile); }
async function generate(id,req,manual=true) { if(manual && !canManage(req.profile)) throw fail("You do not have permission to generate recurring work.",403); const {data,error}=await supabaseAdmin.rpc("generate_recurring_work",{p_schedule_id:id,p_actor:req?.user?.id||null,p_manual:manual}); if(error) throw error; if(data?.status==="generated" && data.assignedUserId) await notifyRegisterUser({recipientProfileId:data.assignedUserId,eventKey:`recurring:generated:${data.occurrenceId}`,eventType:"Recurring Work Created",title:data.period,message:`Recurring work for ${data.period} has been created and assigned to you.`,route:`/?page=files&file=${data.fileId}`,category:"assignments",actor:{authUserId:req?.user?.id,name:req?.profile?.name||"System"}}); return data; }
async function control(id,action,input,req) { if(!canManage(req.profile)) throw fail("Only authorized managers can change a recurring schedule.",403); const {schedule:before}=await getSchedule(id,req.profile); let patch={updated_by:req.user.id,updated_at:new Date().toISOString()};
  if(action==="pause"){if(!clean(input.reason))throw fail("Pause reason is required.");Object.assign(patch,{paused:true,pause_date:dateOnly(input.pauseDate)||isoDate(new Date()),pause_reason:clean(input.reason,1000)});}
  else if(action==="resume"){if(!["missed","current"].includes(input.mode))throw fail("Choose how missed periods should be handled.");Object.assign(patch,{paused:false,pause_date:null,pause_reason:null});if(input.mode==="current"){const today=isoDate(new Date());let p=before.next_period_start;while(p<today)p=nextPeriod(p,before.frequency,before.interval_value);const end=periodEnd(p,before.frequency,before.interval_value);const due=ruleDate(p,end,before.due_date_rule);Object.assign(patch,{next_period_start:p,next_work_period:periodLabel(p,before.frequency,before.interval_value),next_generation_date:`${addDays(due,-before.generate_before_days)}T00:00:00.000Z`});}}
  else if(action==="end"){if(!clean(input.reason))throw fail("End reason is required.");Object.assign(patch,{active:false,ended_at:new Date().toISOString(),end_reason:clean(input.reason,1000),end_date:dateOnly(input.endDate)||before.end_date});}
  else if(action==="skip"){if(!clean(input.reason))throw fail("Skip reason is required.");const end=periodEnd(before.next_period_start,before.frequency,before.interval_value);const due=ruleDate(before.next_period_start,end,before.due_date_rule);const {data:occ,error:occError}=await supabaseAdmin.from("recurring_work_occurrences").insert({recurring_schedule_id:id,client_id:before.client_id,service_type:before.service_type,work_type:before.work_type,work_period:before.next_work_period,period_start:before.next_period_start,period_end:end,financial_year:financialYear(before.next_period_start),scheduled_generation_date:before.next_generation_date,statutory_due_date:due,status:"Skipped",skip_reason:clean(input.reason,1000),generated_by:req.user.id}).select("id").single();if(occError)throw occError;const p=nextPeriod(before.next_period_start,before.frequency,before.interval_value),pEnd=periodEnd(p,before.frequency,before.interval_value),pDue=ruleDate(p,pEnd,before.due_date_rule);Object.assign(patch,{next_period_start:p,next_work_period:periodLabel(p,before.frequency,before.interval_value),next_generation_date:`${addDays(pDue,-before.generate_before_days)}T00:00:00.000Z`});await audit(id,"Occurrence skipped",req,{period:before.next_work_period},{reason:input.reason},occ.id);}
  else throw fail("Unsupported schedule action."); const {data,error}=await supabaseAdmin.from("recurring_work_schedules").update(patch).eq("id",id).select("*").single();if(error)throw error;if(action!=="skip")await audit(id,action[0].toUpperCase()+action.slice(1),req,before,data);return getSchedule(id,req.profile); }
async function listOccurrences(filters={},profile={}) { const page=Math.max(1,Number(filters.page)||1),pageSize=Math.min(100,Math.max(10,Number(filters.pageSize)||25)); let query=supabaseAdmin.from("recurring_work_occurrences").select("*,schedule:recurring_work_schedules!inner(client_name,assigned_staff_id,assigned_team,frequency)",{count:"exact"}); if(!canManage(profile))query=query.eq("schedule.assigned_staff_id",profile.id); if(filters.status)query=query.eq("status",filters.status); if(filters.scheduleId)query=query.eq("recurring_schedule_id",filters.scheduleId); if(filters.from)query=query.gte("statutory_due_date",filters.from); if(filters.to)query=query.lte("statutory_due_date",filters.to); const from=(page-1)*pageSize;const {data,error,count}=await query.order("created_at",{ascending:false}).range(from,from+pageSize-1);if(error)throw error;return{occurrences:data||[],total:count||0,page,pageSize,pageCount:Math.max(1,Math.ceil((count||0)/pageSize))}; }
async function dashboard(profile={}) { const schedules=await listSchedules({page:1,pageSize:100},profile);const rows=schedules.schedules;const today=isoDate(new Date()),week=addDays(today,7),month=addDays(today,30);const {count:errorCount,error}=await supabaseAdmin.from("recurring_work_occurrences").select("id",{count:"exact",head:true}).eq("status","Failed");if(error)throw error;const {count:completedCount,error:completedError}=await supabaseAdmin.from("recurring_work_occurrences").select("id",{count:"exact",head:true}).in("status",["Generated","Manually Generated"]).gte("actual_generation_date",`${today.slice(0,7)}-01`);if(completedError)throw completedError;return{active:rows.filter(x=>x.active&&!x.paused&&!x.ended_at).length,generatingToday:rows.filter(x=>String(x.next_generation_date).slice(0,10)===today).length,dueThisWeek:rows.filter(x=>String(x.next_generation_date).slice(0,10)<=week).length,dueThisMonth:rows.filter(x=>String(x.next_generation_date).slice(0,10)<=month).length,errors:Number(errorCount)||0,paused:rows.filter(x=>x.paused).length,completedThisMonth:Number(completedCount)||0,upcoming7:rows.filter(x=>x.active&&!x.paused&&String(x.next_generation_date).slice(0,10)<=week).slice(0,10),upcoming30:rows.filter(x=>x.active&&!x.paused&&String(x.next_generation_date).slice(0,10)<=month).slice(0,30),byService:group(rows,"service_type"),byStaff:group(rows,x=>x.assigned?.name||x.assigned_team||"Unassigned")}; }
function group(rows,key){const out={};for(const row of rows){const label=typeof key==="function"?key(row):row[key]||"Not specified";out[label]=(out[label]||0)+1;}return Object.entries(out).map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value).slice(0,10);}
async function templates(includeInactive=false){let q=supabaseAdmin.from("recurring_work_templates").select("*").order("name");if(!includeInactive)q=q.eq("active",true);const{data,error}=await q;if(error)throw error;return data||[];}
async function saveTemplate(input,req){if(!canManage(req.profile))throw fail("Only authorized managers can manage templates.",403);const name=clean(input.name,160),service=clean(input.serviceType||input.service_type,160),frequency=input.frequency;if(!name||!service||!FREQUENCIES.includes(frequency))throw fail("Template Name, Service and Frequency are required.");const payload={name,service_type:service,work_type:clean(input.workType||input.work_type,160)||null,frequency,interval_value:Math.max(1,Number(input.intervalValue)||1),due_date_rule:normalizeRule(input,"dueDateRule",0),internal_target_rule:normalizeRule(input,"internalTargetRule",-3),document_due_rule:normalizeRule(input,"documentDueRule",-7),generate_before_days:Math.max(0,Number(input.generateBeforeDays)||0),checklist:Array.isArray(input.checklist)?input.checklist:[],productivity_weight:Number(input.productivityWeight)||1,assigned_team:clean(input.assignedTeam,160)||null,standard_tat:Number(input.standardTat)||null,billing_frequency:BILLING.includes(input.billingFrequency)?input.billingFrequency:"No automatic billing",active:input.active!==false,updated_by:req.user.id,updated_at:new Date().toISOString()};let q=input.id?supabaseAdmin.from("recurring_work_templates").update(payload).eq("id",input.id):supabaseAdmin.from("recurring_work_templates").insert({...payload,created_by:req.user.id});const{data,error}=await q.select("*").single();if(error)throw error;return data;}
async function settings(){const{data,error}=await supabaseAdmin.from("recurring_work_settings").select("*").eq("id","default").single();if(error)throw error;return data;}
async function saveSettings(input,req){if(req.profile.role!=="Admin")throw fail("Only Admin can change recurring-work settings.",403);const payload={weekend_rule:input.weekendRule||input.weekend_rule||"Keep original date",inactive_client_action:input.inactiveClientAction||input.inactive_client_action||"Ask administrator",automatic_document_reminders:Boolean(input.automaticDocumentReminders??input.automatic_document_reminders),scheduler_enabled:Boolean(input.schedulerEnabled??input.scheduler_enabled),updated_by:req.user.id,updated_at:new Date().toISOString()};const{data,error}=await supabaseAdmin.from("recurring_work_settings").update(payload).eq("id","default").select("*").single();if(error)throw error;return data;}
async function processDueSchedules(limit=50){const cfg=await settings();if(!cfg.scheduler_enabled)return{disabled:true,processed:0};const{data,error}=await supabaseAdmin.from("recurring_work_schedules").select("id,next_period_start,work_type,client_id,service_type,next_generation_date").eq("active",true).eq("paused",false).is("ended_at",null).lte("next_generation_date",new Date().toISOString()).order("next_generation_date").limit(limit);if(error)throw error;const results=[];for(const schedule of data||[]){try{results.push(await generate(schedule,null,false));}catch(err){const end=periodEnd(schedule.next_period_start,"Monthly",1);await supabaseAdmin.from("recurring_work_occurrences").upsert({recurring_schedule_id:schedule.id,client_id:schedule.client_id,service_type:schedule.service_type,work_type:schedule.work_type,work_period:schedule.next_period_start,period_start:schedule.next_period_start,period_end:end,financial_year:financialYear(schedule.next_period_start),scheduled_generation_date:schedule.next_generation_date,status:"Failed",error_message:clean(err.message,2000),updated_at:new Date().toISOString()},{onConflict:"recurring_schedule_id,period_start,work_type"});results.push({status:"failed",scheduleId:schedule.id,error:err.message});}}return{processed:results.length,results};}

module.exports={FREQUENCIES,BILLING,RULES,canManage,listSchedules,getSchedule,createSchedule,updateSchedule,generate,control,listOccurrences,dashboard,templates,saveTemplate,settings,saveSettings,processDueSchedules,periodEnd,nextPeriod,financialYear,periodLabel,ruleDate};
